# Generated by Django 4.1 on 2022-08-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
