# Generated by Django 4.1 on 2022-08-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro', '0002_clientes_delete_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
